version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
      - monitor_sensors:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: sensors
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sensors

volumes:
  monitor_sensors:
